// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#ifndef PROTOBUF_config_2eproto__INCLUDED
#define PROTOBUF_config_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace dn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_config_2eproto();
void protobuf_AssignDesc_config_2eproto();
void protobuf_ShutdownFile_config_2eproto();

class module_lst;
class proxy_conf;
class node_desc;
class local_node_conf;

enum node_desc_InetProto {
  node_desc_InetProto_TCP = 0,
  node_desc_InetProto_UDP = 1
};
bool node_desc_InetProto_IsValid(int value);
const node_desc_InetProto node_desc_InetProto_InetProto_MIN = node_desc_InetProto_TCP;
const node_desc_InetProto node_desc_InetProto_InetProto_MAX = node_desc_InetProto_UDP;
const int node_desc_InetProto_InetProto_ARRAYSIZE = node_desc_InetProto_InetProto_MAX + 1;

const ::google::protobuf::EnumDescriptor* node_desc_InetProto_descriptor();
inline const ::std::string& node_desc_InetProto_Name(node_desc_InetProto value) {
  return ::google::protobuf::internal::NameOfEnum(
    node_desc_InetProto_descriptor(), value);
}
inline bool node_desc_InetProto_Parse(
    const ::std::string& name, node_desc_InetProto* value) {
  return ::google::protobuf::internal::ParseNamedEnum<node_desc_InetProto>(
    node_desc_InetProto_descriptor(), name, value);
}
// ===================================================================

class module_lst : public ::google::protobuf::Message {
 public:
  module_lst();
  virtual ~module_lst();
  
  module_lst(const module_lst& from);
  
  inline module_lst& operator=(const module_lst& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const module_lst& default_instance();
  
  void Swap(module_lst* other);
  
  // implements Message ----------------------------------------------
  
  module_lst* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const module_lst& from);
  void MergeFrom(const module_lst& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated string module_file = 1;
  inline int module_file_size() const;
  inline void clear_module_file();
  static const int kModuleFileFieldNumber = 1;
  inline const ::std::string& module_file(int index) const;
  inline ::std::string* mutable_module_file(int index);
  inline void set_module_file(int index, const ::std::string& value);
  inline void set_module_file(int index, const char* value);
  inline void set_module_file(int index, const char* value, size_t size);
  inline ::std::string* add_module_file();
  inline void add_module_file(const ::std::string& value);
  inline void add_module_file(const char* value);
  inline void add_module_file(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& module_file() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_module_file();
  
  // @@protoc_insertion_point(class_scope:dn.module_lst)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::std::string> module_file_;
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static module_lst* default_instance_;
};
// -------------------------------------------------------------------

class proxy_conf : public ::google::protobuf::Message {
 public:
  proxy_conf();
  virtual ~proxy_conf();
  
  proxy_conf(const proxy_conf& from);
  
  inline proxy_conf& operator=(const proxy_conf& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const proxy_conf& default_instance();
  
  void Swap(proxy_conf* other);
  
  // implements Message ----------------------------------------------
  
  proxy_conf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proxy_conf& from);
  void MergeFrom(const proxy_conf& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string addr = 1;
  inline bool has_addr() const;
  inline void clear_addr();
  static const int kAddrFieldNumber = 1;
  inline const ::std::string& addr() const;
  inline void set_addr(const ::std::string& value);
  inline void set_addr(const char* value);
  inline void set_addr(const char* value, size_t size);
  inline ::std::string* mutable_addr();
  
  // required string port = 2;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 2;
  inline const ::std::string& port() const;
  inline void set_port(const ::std::string& value);
  inline void set_port(const char* value);
  inline void set_port(const char* value, size_t size);
  inline ::std::string* mutable_port();
  
  // required int32 max_conn = 3;
  inline bool has_max_conn() const;
  inline void clear_max_conn();
  static const int kMaxConnFieldNumber = 3;
  inline ::google::protobuf::int32 max_conn() const;
  inline void set_max_conn(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:dn.proxy_conf)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* addr_;
  static const ::std::string _default_addr_;
  ::std::string* port_;
  static const ::std::string _default_port_;
  ::google::protobuf::int32 max_conn_;
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static proxy_conf* default_instance_;
};
// -------------------------------------------------------------------

class node_desc : public ::google::protobuf::Message {
 public:
  node_desc();
  virtual ~node_desc();
  
  node_desc(const node_desc& from);
  
  inline node_desc& operator=(const node_desc& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const node_desc& default_instance();
  
  void Swap(node_desc* other);
  
  // implements Message ----------------------------------------------
  
  node_desc* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const node_desc& from);
  void MergeFrom(const node_desc& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef node_desc_InetProto InetProto;
  static const InetProto TCP = node_desc_InetProto_TCP;
  static const InetProto UDP = node_desc_InetProto_UDP;
  static inline bool InetProto_IsValid(int value) {
    return node_desc_InetProto_IsValid(value);
  }
  static const InetProto InetProto_MIN =
    node_desc_InetProto_InetProto_MIN;
  static const InetProto InetProto_MAX =
    node_desc_InetProto_InetProto_MAX;
  static const int InetProto_ARRAYSIZE =
    node_desc_InetProto_InetProto_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  InetProto_descriptor() {
    return node_desc_InetProto_descriptor();
  }
  static inline const ::std::string& InetProto_Name(InetProto value) {
    return node_desc_InetProto_Name(value);
  }
  static inline bool InetProto_Parse(const ::std::string& name,
      InetProto* value) {
    return node_desc_InetProto_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required string id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::std::string& id() const;
  inline void set_id(const ::std::string& value);
  inline void set_id(const char* value);
  inline void set_id(const char* value, size_t size);
  inline ::std::string* mutable_id();
  
  // required string addr = 2;
  inline bool has_addr() const;
  inline void clear_addr();
  static const int kAddrFieldNumber = 2;
  inline const ::std::string& addr() const;
  inline void set_addr(const ::std::string& value);
  inline void set_addr(const char* value);
  inline void set_addr(const char* value, size_t size);
  inline ::std::string* mutable_addr();
  
  // required uint64 ping_time = 3;
  inline bool has_ping_time() const;
  inline void clear_ping_time();
  static const int kPingTimeFieldNumber = 3;
  inline ::google::protobuf::uint64 ping_time() const;
  inline void set_ping_time(::google::protobuf::uint64 value);
  
  // required .dn.node_desc.InetProto proto = 4;
  inline bool has_proto() const;
  inline void clear_proto();
  static const int kProtoFieldNumber = 4;
  inline ::dn::node_desc_InetProto proto() const;
  inline void set_proto(::dn::node_desc_InetProto value);
  
  // required int32 port = 5;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 5;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:dn.node_desc)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* id_;
  static const ::std::string _default_id_;
  ::std::string* addr_;
  static const ::std::string _default_addr_;
  ::google::protobuf::uint64 ping_time_;
  int proto_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static node_desc* default_instance_;
};
// -------------------------------------------------------------------

class local_node_conf : public ::google::protobuf::Message {
 public:
  local_node_conf();
  virtual ~local_node_conf();
  
  local_node_conf(const local_node_conf& from);
  
  inline local_node_conf& operator=(const local_node_conf& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const local_node_conf& default_instance();
  
  void Swap(local_node_conf* other);
  
  // implements Message ----------------------------------------------
  
  local_node_conf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const local_node_conf& from);
  void MergeFrom(const local_node_conf& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .dn.node_desc local = 1;
  inline bool has_local() const;
  inline void clear_local();
  static const int kLocalFieldNumber = 1;
  inline const ::dn::node_desc& local() const;
  inline ::dn::node_desc* mutable_local();
  
  // repeated .dn.node_desc others = 2;
  inline int others_size() const;
  inline void clear_others();
  static const int kOthersFieldNumber = 2;
  inline const ::dn::node_desc& others(int index) const;
  inline ::dn::node_desc* mutable_others(int index);
  inline ::dn::node_desc* add_others();
  inline const ::google::protobuf::RepeatedPtrField< ::dn::node_desc >&
      others() const;
  inline ::google::protobuf::RepeatedPtrField< ::dn::node_desc >*
      mutable_others();
  
  // @@protoc_insertion_point(class_scope:dn.local_node_conf)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::dn::node_desc* local_;
  ::google::protobuf::RepeatedPtrField< ::dn::node_desc > others_;
  friend void  protobuf_AddDesc_config_2eproto();
  friend void protobuf_AssignDesc_config_2eproto();
  friend void protobuf_ShutdownFile_config_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static local_node_conf* default_instance_;
};
// ===================================================================


// ===================================================================

// module_lst

// repeated string module_file = 1;
inline int module_lst::module_file_size() const {
  return module_file_.size();
}
inline void module_lst::clear_module_file() {
  module_file_.Clear();
}
inline const ::std::string& module_lst::module_file(int index) const {
  return module_file_.Get(index);
}
inline ::std::string* module_lst::mutable_module_file(int index) {
  return module_file_.Mutable(index);
}
inline void module_lst::set_module_file(int index, const ::std::string& value) {
  module_file_.Mutable(index)->assign(value);
}
inline void module_lst::set_module_file(int index, const char* value) {
  module_file_.Mutable(index)->assign(value);
}
inline void module_lst::set_module_file(int index, const char* value, size_t size) {
  module_file_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* module_lst::add_module_file() {
  return module_file_.Add();
}
inline void module_lst::add_module_file(const ::std::string& value) {
  module_file_.Add()->assign(value);
}
inline void module_lst::add_module_file(const char* value) {
  module_file_.Add()->assign(value);
}
inline void module_lst::add_module_file(const char* value, size_t size) {
  module_file_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
module_lst::module_file() const {
  return module_file_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
module_lst::mutable_module_file() {
  return &module_file_;
}

// -------------------------------------------------------------------

// proxy_conf

// required string addr = 1;
inline bool proxy_conf::has_addr() const {
  return _has_bit(0);
}
inline void proxy_conf::clear_addr() {
  if (addr_ != &_default_addr_) {
    addr_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& proxy_conf::addr() const {
  return *addr_;
}
inline void proxy_conf::set_addr(const ::std::string& value) {
  _set_bit(0);
  if (addr_ == &_default_addr_) {
    addr_ = new ::std::string;
  }
  addr_->assign(value);
}
inline void proxy_conf::set_addr(const char* value) {
  _set_bit(0);
  if (addr_ == &_default_addr_) {
    addr_ = new ::std::string;
  }
  addr_->assign(value);
}
inline void proxy_conf::set_addr(const char* value, size_t size) {
  _set_bit(0);
  if (addr_ == &_default_addr_) {
    addr_ = new ::std::string;
  }
  addr_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* proxy_conf::mutable_addr() {
  _set_bit(0);
  if (addr_ == &_default_addr_) {
    addr_ = new ::std::string;
  }
  return addr_;
}

// required string port = 2;
inline bool proxy_conf::has_port() const {
  return _has_bit(1);
}
inline void proxy_conf::clear_port() {
  if (port_ != &_default_port_) {
    port_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& proxy_conf::port() const {
  return *port_;
}
inline void proxy_conf::set_port(const ::std::string& value) {
  _set_bit(1);
  if (port_ == &_default_port_) {
    port_ = new ::std::string;
  }
  port_->assign(value);
}
inline void proxy_conf::set_port(const char* value) {
  _set_bit(1);
  if (port_ == &_default_port_) {
    port_ = new ::std::string;
  }
  port_->assign(value);
}
inline void proxy_conf::set_port(const char* value, size_t size) {
  _set_bit(1);
  if (port_ == &_default_port_) {
    port_ = new ::std::string;
  }
  port_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* proxy_conf::mutable_port() {
  _set_bit(1);
  if (port_ == &_default_port_) {
    port_ = new ::std::string;
  }
  return port_;
}

// required int32 max_conn = 3;
inline bool proxy_conf::has_max_conn() const {
  return _has_bit(2);
}
inline void proxy_conf::clear_max_conn() {
  max_conn_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 proxy_conf::max_conn() const {
  return max_conn_;
}
inline void proxy_conf::set_max_conn(::google::protobuf::int32 value) {
  _set_bit(2);
  max_conn_ = value;
}

// -------------------------------------------------------------------

// node_desc

// required string id = 1;
inline bool node_desc::has_id() const {
  return _has_bit(0);
}
inline void node_desc::clear_id() {
  if (id_ != &_default_id_) {
    id_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& node_desc::id() const {
  return *id_;
}
inline void node_desc::set_id(const ::std::string& value) {
  _set_bit(0);
  if (id_ == &_default_id_) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void node_desc::set_id(const char* value) {
  _set_bit(0);
  if (id_ == &_default_id_) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void node_desc::set_id(const char* value, size_t size) {
  _set_bit(0);
  if (id_ == &_default_id_) {
    id_ = new ::std::string;
  }
  id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* node_desc::mutable_id() {
  _set_bit(0);
  if (id_ == &_default_id_) {
    id_ = new ::std::string;
  }
  return id_;
}

// required string addr = 2;
inline bool node_desc::has_addr() const {
  return _has_bit(1);
}
inline void node_desc::clear_addr() {
  if (addr_ != &_default_addr_) {
    addr_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& node_desc::addr() const {
  return *addr_;
}
inline void node_desc::set_addr(const ::std::string& value) {
  _set_bit(1);
  if (addr_ == &_default_addr_) {
    addr_ = new ::std::string;
  }
  addr_->assign(value);
}
inline void node_desc::set_addr(const char* value) {
  _set_bit(1);
  if (addr_ == &_default_addr_) {
    addr_ = new ::std::string;
  }
  addr_->assign(value);
}
inline void node_desc::set_addr(const char* value, size_t size) {
  _set_bit(1);
  if (addr_ == &_default_addr_) {
    addr_ = new ::std::string;
  }
  addr_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* node_desc::mutable_addr() {
  _set_bit(1);
  if (addr_ == &_default_addr_) {
    addr_ = new ::std::string;
  }
  return addr_;
}

// required uint64 ping_time = 3;
inline bool node_desc::has_ping_time() const {
  return _has_bit(2);
}
inline void node_desc::clear_ping_time() {
  ping_time_ = GOOGLE_ULONGLONG(0);
  _clear_bit(2);
}
inline ::google::protobuf::uint64 node_desc::ping_time() const {
  return ping_time_;
}
inline void node_desc::set_ping_time(::google::protobuf::uint64 value) {
  _set_bit(2);
  ping_time_ = value;
}

// required .dn.node_desc.InetProto proto = 4;
inline bool node_desc::has_proto() const {
  return _has_bit(3);
}
inline void node_desc::clear_proto() {
  proto_ = 0;
  _clear_bit(3);
}
inline ::dn::node_desc_InetProto node_desc::proto() const {
  return static_cast< ::dn::node_desc_InetProto >(proto_);
}
inline void node_desc::set_proto(::dn::node_desc_InetProto value) {
  GOOGLE_DCHECK(::dn::node_desc_InetProto_IsValid(value));
  _set_bit(3);
  proto_ = value;
}

// required int32 port = 5;
inline bool node_desc::has_port() const {
  return _has_bit(4);
}
inline void node_desc::clear_port() {
  port_ = 0;
  _clear_bit(4);
}
inline ::google::protobuf::int32 node_desc::port() const {
  return port_;
}
inline void node_desc::set_port(::google::protobuf::int32 value) {
  _set_bit(4);
  port_ = value;
}

// -------------------------------------------------------------------

// local_node_conf

// required .dn.node_desc local = 1;
inline bool local_node_conf::has_local() const {
  return _has_bit(0);
}
inline void local_node_conf::clear_local() {
  if (local_ != NULL) local_->::dn::node_desc::Clear();
  _clear_bit(0);
}
inline const ::dn::node_desc& local_node_conf::local() const {
  return local_ != NULL ? *local_ : *default_instance_->local_;
}
inline ::dn::node_desc* local_node_conf::mutable_local() {
  _set_bit(0);
  if (local_ == NULL) local_ = new ::dn::node_desc;
  return local_;
}

// repeated .dn.node_desc others = 2;
inline int local_node_conf::others_size() const {
  return others_.size();
}
inline void local_node_conf::clear_others() {
  others_.Clear();
}
inline const ::dn::node_desc& local_node_conf::others(int index) const {
  return others_.Get(index);
}
inline ::dn::node_desc* local_node_conf::mutable_others(int index) {
  return others_.Mutable(index);
}
inline ::dn::node_desc* local_node_conf::add_others() {
  return others_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::dn::node_desc >&
local_node_conf::others() const {
  return others_;
}
inline ::google::protobuf::RepeatedPtrField< ::dn::node_desc >*
local_node_conf::mutable_others() {
  return &others_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dn

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dn::node_desc_InetProto>() {
  return ::dn::node_desc_InetProto_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_config_2eproto__INCLUDED
