let M={
    CLOSED_SESSION:1,
    CLOSE_ALL_SESSION:2,
    
    SEND_MSG_TO_USER:3,
    SEND_MSG_TO_SOME_USER:4,
    SEND_MSG_TO_ALL_USER:5,

    SEND_MSG_TO_USER_THEN_CLOSE:6,
    SEND_MSG_TO_SOME_USER_THEN_CLOSE:7,
    SEND_MSG_TO_ALL_USER_THEN_CLOSE:8,

    
    CONNECT_RESULT:100,
    ACCEPT_RESULT:101,
    RECV_MSG_FROM_USER:102,
    USER_CONN_CLOSE:103
    
}
module.exports = M